Repository maasglobal/maas-schemas, pull requests merged in 2018-10, with the labels that each got.

#326 Fix schema id typo
  package.json
  schemas/maas-backend/itineraries/itinerary-update/response.json
Labels: bug

#324 Ensure initialized schema is in all cases the same
  gulpfile.js
  index.js
  package.json
  test-lib.js
  test/feature-require-schemas.js
  test/feature-validate.js
  test/schemas/core/address.js
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, bug

#331 Ensure to not change input object on validation
  lib/validator.js
  package.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, bug

#333 Allow email address up to 255 characters
  schemas/core/components/units.json
Labels: PR: Waiting for Review

#332 Customer's payment source update
  package.json
  schemas/maas-backend/customers/payment-sources/paymentSource.json
  schemas/maas-backend/customers/payment-sources/update/request.json
  schemas/maas-backend/customers/payment-sources/update/response.json
Labels: PR: Waiting for Review
