Repository maasglobal/maas-schemas, pull requests merged in 2018-04, with the labels that each got.

#239 Station schema
  prebuilt/core/components/station.json
  prebuilt/tsp/stations-list/request.json
  prebuilt/tsp/stations-list/response.json
  prebuilt/tsp/stations-retrieve/request.json
  prebuilt/tsp/stations-retrieve/response.json
  schemas/core/components/station.json
  schemas/tsp/stations-list/request.json
  schemas/tsp/stations-list/response.json
  schemas/tsp/stations-retrieve/request.json
  schemas/tsp/stations-retrieve/response.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#241 Stations backend schema
  prebuilt/maas-backend/stations/stations-list/request.json
  prebuilt/maas-backend/stations/stations-list/response.json
  prebuilt/maas-backend/stations/stations-retrieve/request.json
  prebuilt/maas-backend/stations/stations-retrieve/response.json
  schemas/maas-backend/stations/stations-list/request.json
  schemas/maas-backend/stations/stations-list/response.json
  schemas/maas-backend/stations/stations-retrieve/request.json
  schemas/maas-backend/stations/stations-retrieve/response.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#243 Tsp journey planner support
  prebuilt/tsp/journey-planner/request.json
  prebuilt/tsp/journey-planner/response.json
  schemas/tsp/journey-planner/request.json
  schemas/tsp/journey-planner/response.json
Labels: PR: Can be merged by the reviewer

#250 terms.fareRates extension
  prebuilt/core/booking.json
  prebuilt/core/components/terms.json
  prebuilt/core/itinerary.json
  prebuilt/core/plan.json
  prebuilt/core/product-option.json
  prebuilt/maas-backend/bookings/bookings-agency-options/response.json
  prebuilt/maas-backend/bookings/bookings-cancel/response.json
  prebuilt/maas-backend/bookings/bookings-create/request.json
  prebuilt/maas-backend/bookings/bookings-create/response.json
  prebuilt/maas-backend/bookings/bookings-list/response.json
  prebuilt/maas-backend/bookings/bookings-retrieve/response.json
  prebuilt/maas-backend/bookings/bookings-update/request.json
  prebuilt/maas-backend/bookings/bookings-update/response.json
  prebuilt/maas-backend/itineraries/itinerary-create/request.json
  prebuilt/maas-backend/itineraries/itinerary-create/response.json
  prebuilt/maas-backend/itineraries/itinerary-list/response.json
  prebuilt/maas-backend/itineraries/itinerary-retrieve/response.json
  prebuilt/maas-backend/provider/routes/response.json
  prebuilt/maas-backend/routes/routes-query/response.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/request.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/response.json
  prebuilt/tsp/booking-cancel/response.json
  prebuilt/tsp/booking-create/request.json
  prebuilt/tsp/booking-create/response.json
  prebuilt/tsp/booking-option.json
  prebuilt/tsp/booking-options-list/response.json
  prebuilt/tsp/booking-read-by-id/response.json
  prebuilt/tsp/booking-update/response.json
  prebuilt/tsp/webhooks-bookings-update/remote-request.json
  prebuilt/tsp/webhooks-bookings-update/remote-response.json
  schemas/core/components/terms.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#253 Support optional place.facilities and place.openningHours
  prebuilt/core/booking.json
  prebuilt/core/components/units-geo.json
  prebuilt/core/itinerary.json
  prebuilt/core/leg.json
  prebuilt/core/plan.json
  prebuilt/core/profile.json
  prebuilt/maas-backend/bookings/bookings-agency-options/response.json
  prebuilt/maas-backend/bookings/bookings-cancel/response.json
  prebuilt/maas-backend/bookings/bookings-create/request.json
  prebuilt/maas-backend/bookings/bookings-create/response.json
  prebuilt/maas-backend/bookings/bookings-list/response.json
  prebuilt/maas-backend/bookings/bookings-retrieve/response.json
  prebuilt/maas-backend/bookings/bookings-update/request.json
  prebuilt/maas-backend/bookings/bookings-update/response.json
  prebuilt/maas-backend/itineraries/itinerary-create/request.json
  prebuilt/maas-backend/itineraries/itinerary-create/response.json
  prebuilt/maas-backend/itineraries/itinerary-list/response.json
  prebuilt/maas-backend/itineraries/itinerary-retrieve/response.json
  prebuilt/maas-backend/profile/profile-edit/response.json
  prebuilt/maas-backend/profile/profile-favoriteLocations-add/request.json
  prebuilt/maas-backend/profile/profile-favoriteLocations-add/response.json
  prebuilt/maas-backend/profile/profile-favoriteLocations-delete/response.json
  prebuilt/maas-backend/profile/profile-webhook/response.json
  prebuilt/maas-backend/provider/routes/response.json
  prebuilt/maas-backend/routes/routes-query/response.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/request.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/response.json
  prebuilt/tsp/booking-cancel/response.json
  prebuilt/tsp/booking-create/request.json
  prebuilt/tsp/booking-create/response.json
  prebuilt/tsp/booking-option.json
  prebuilt/tsp/booking-options-list/response.json
  prebuilt/tsp/booking-read-by-id/response.json
  prebuilt/tsp/booking-update/response.json
  prebuilt/tsp/webhooks-bookings-update/remote-request.json
  prebuilt/tsp/webhooks-bookings-update/remote-response.json
  schemas/core/components/units-geo.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#252 Support startTimeReturn + endTimeReturn in terms.validity
  prebuilt/core/booking.json
  prebuilt/core/components/terms.json
  prebuilt/core/itinerary.json
  prebuilt/core/plan.json
  prebuilt/core/product-option.json
  prebuilt/maas-backend/bookings/bookings-agency-options/response.json
  prebuilt/maas-backend/bookings/bookings-cancel/response.json
  prebuilt/maas-backend/bookings/bookings-create/request.json
  prebuilt/maas-backend/bookings/bookings-create/response.json
  prebuilt/maas-backend/bookings/bookings-list/response.json
  prebuilt/maas-backend/bookings/bookings-retrieve/response.json
  prebuilt/maas-backend/bookings/bookings-update/request.json
  prebuilt/maas-backend/bookings/bookings-update/response.json
  prebuilt/maas-backend/itineraries/itinerary-create/request.json
  prebuilt/maas-backend/itineraries/itinerary-create/response.json
  prebuilt/maas-backend/itineraries/itinerary-list/response.json
  prebuilt/maas-backend/itineraries/itinerary-retrieve/response.json
  prebuilt/maas-backend/provider/routes/response.json
  prebuilt/maas-backend/routes/routes-query/response.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/request.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/response.json
  prebuilt/tsp/booking-cancel/response.json
  prebuilt/tsp/booking-create/request.json
  prebuilt/tsp/booking-create/response.json
  prebuilt/tsp/booking-option.json
  prebuilt/tsp/booking-options-list/response.json
  prebuilt/tsp/booking-read-by-id/response.json
  prebuilt/tsp/booking-update/response.json
  prebuilt/tsp/webhooks-bookings-update/remote-request.json
  prebuilt/tsp/webhooks-bookings-update/remote-response.json
  schemas/core/components/terms.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#254 Adds extraOptions to booking option list request
  prebuilt/tsp/booking-options-list/request.json
  schemas/tsp/booking-options-list/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#247 Configurator and supports
  prebuilt/core/booking.json
  prebuilt/core/components/configurator.json
  prebuilt/core/components/customer.json
  prebuilt/core/itinerary.json
  prebuilt/core/plan.json
  prebuilt/core/product-option.json
  prebuilt/maas-backend/bookings/bookings-agency-options/response.json
  prebuilt/maas-backend/bookings/bookings-cancel/response.json
  prebuilt/maas-backend/bookings/bookings-create/request.json
  prebuilt/maas-backend/bookings/bookings-create/response.json
  prebuilt/maas-backend/bookings/bookings-list/response.json
  prebuilt/maas-backend/bookings/bookings-retrieve/response.json
  prebuilt/maas-backend/bookings/bookings-update/request.json
  prebuilt/maas-backend/bookings/bookings-update/response.json
  prebuilt/maas-backend/itineraries/itinerary-create/request.json
  prebuilt/maas-backend/itineraries/itinerary-create/response.json
  prebuilt/maas-backend/itineraries/itinerary-list/response.json
  prebuilt/maas-backend/itineraries/itinerary-retrieve/response.json
  prebuilt/maas-backend/provider/routes/response.json
  prebuilt/maas-backend/routes/routes-query/response.json
  prebuilt/maas-backend/webhooks/webhooks-bookings-update/response.json
  prebuilt/tsp/booking-create/request.json
  prebuilt/tsp/booking-create/response.json
  prebuilt/tsp/booking-option.json
  prebuilt/tsp/booking-options-list/response.json
  prebuilt/tsp/webhooks-bookings-update/remote-response.json
  schemas/core/booking.json
  schemas/core/components/configurator.json
  schemas/core/components/configurator.md
  schemas/core/components/customer.json
  schemas/core/product-option.json
  schemas/maas-backend/bookings/bookings-agency-options/response.json
  schemas/maas-backend/bookings/bookings-create/request.json
  schemas/maas-backend/itineraries/itinerary-create/request.json
  schemas/tsp/booking-create/request.json
  schemas/tsp/booking-create/response.json
  schemas/tsp/booking-option.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#257 Modify empty configurator rule
  prebuilt/core/booking.json
  prebuilt/core/components/configurator.json
  prebuilt/core/itinerary.json
  prebuilt/core/plan.json
  prebuilt/core/product-option.json
  prebuilt/maas-backend/bookings/bookings-agency-options/response.json
  prebuilt/maas-backend/bookings/bookings-cancel/response.json
  prebuilt/maas-backend/bookings/bookings-create/request.json
  prebuilt/maas-backend/bookings/bookings-create/response.json
  prebuilt/maas-backend/bookings/bookings-list/response.json
  prebuilt/maas-backend/bookings/bookings-retrieve/response.json
  prebuilt/maas-backend/bookings/bookings-update/request.json
  prebuilt/maas-backend/bookings/bookings-update/response.json
  prebuilt/maas-backend/itineraries/itinerary-create/request.json
  prebuilt/maas-backend/itineraries/itinerary-create/response.json
  prebuilt/maas-backend/itineraries/itinerary-list/response.json
  prebuilt/maas-backend/itineraries/itinerary-retrieve/response.json
  prebuilt/maas-backend/provider/routes/response.json
  prebuilt/maas-backend/routes/routes-query/response.json
  prebuilt/tsp/booking-create/request.json
  prebuilt/tsp/booking-create/response.json
  prebuilt/tsp/booking-option.json
  prebuilt/tsp/booking-options-list/response.json
  schemas/core/components/configurator.json
Labels: bug
