Repository maasglobal/maas-schemas, pull requests merged in 2018-05, with the labels that each got.

#264 Itinerary list accept bookingId as filter
  prebuilt/maas-backend/itineraries/itinerary-list/request.json
  schemas/maas-backend/itineraries/itinerary-list/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#280 Bump version to 1.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#283 Make configurator choice's terms and meta optional
  schemas/core/components/configurator.json
Labels: PR: Can be merged by the reviewer

#287 Supports originalAmount in Cost and productionAmount in Fare
  package.json
  schemas/core/components/cost.json
  schemas/core/components/fare.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#288 Ignore dev and test files when publishing to NPM
  .npmignore
Labels: PR: Waiting for Review
