Repository maasglobal/maas-schemas, pull requests merged in 2018-12, with the labels that each got.

#343 Add paymentParameters, tokenId & token
  schemas/maas-backend/bookings/v2/bookings-create/response.json
  schemas/maas-backend/invoices/invoiceLineItem.json
  test/feature-validate.js
  test/valid-booking-response-v2-payment-parameters.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#345 TSP customer auth
  package.json
  schemas/core/components/common.json
  schemas/tsp/customer-auth/request.json
  schemas/tsp/customer-auth/response.json
Labels: PR: Waiting for Review

#344 In car component allow classification: null
  package.json
  schemas/core/components/car-rental.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, enhancement
