Repository maasglobal/maas-schemas, pull requests merged in 2018-09, with the labels that each got.

#318 v2 bookings create request and response schema
  package.json
  schemas/core/components/units.json
  schemas/maas-backend/bookings/v2/bookings-create/request.json
  schemas/maas-backend/bookings/v2/bookings-create/response.json
Labels: PR: Waiting for Review

#321 Accepting payment source ID for itinerary-create schemas
  package.json
  schemas/maas-backend/itineraries/itinerary-create/request.json
Labels: PR: Can be merged by the reviewer

#322 Add optional radius property to product provider schema
  package.json
  schemas/maas-backend/products/provider.json
Labels: PR: Waiting for Review

#320 Single device and free ticket restriction rules
  package.json
  schemas/core/components/terms.json
Labels: PR: Waiting for Review

#323 Remove legGeometry and recognize distance in options requests
  schemas/tsp/booking-options-list/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review
