Repository maasglobal/maas-schemas, pull requests merged in 2019-10, with the labels that each got.

#415 Version 9
  index.js
  package.json
  schemas/core/booking-meta.json
  schemas/core/booking-option.json
  schemas/core/booking.json
  schemas/core/card.json
  schemas/core/components/address.json
  schemas/core/components/agencyOptions.json
  schemas/core/components/authorization.json
  schemas/core/components/bike-station.json
  schemas/core/components/car-rental.json
  schemas/core/components/configurator.json
  schemas/core/components/cost.json
  schemas/core/components/geolocation.json
  schemas/core/components/personalDataAllowItem.json
  schemas/core/components/place.json
  schemas/core/components/state-log.json
  schemas/core/components/station.json
  schemas/core/components/subscriptionChangeState.json
  schemas/core/components/terms.json
  schemas/core/components/units-geo.json
  schemas/core/iot-thing-shadow.json
  schemas/core/itinerary.json
  schemas/core/leg.json
  schemas/core/modes/MODE_RAIL.json
  schemas/core/paymentSource.json
  schemas/core/plan.json
  schemas/core/product-option.json
  schemas/core/product.json
  schemas/core/profile.json
  schemas/core/region.json
  schemas/core/stop.json
  schemas/maas-backend/autocomplete/autocomplete-query/response.json
  schemas/maas-backend/booking-option-create/response.json
  schemas/maas-backend/bookings/bookings-agency-options/response.json
  schemas/maas-backend/customers/retrieve/response.json
  schemas/maas-backend/customers/update/response.json
  schemas/maas-backend/invoices/invoice.json
  schemas/maas-backend/invoices/invoiceLineItem.json
  schemas/maas-backend/invoices/invoiceUnits.json
  schemas/maas-backend/itineraries/itinerary-create/response.json
  schemas/maas-backend/itineraries/itinerary-list/request.json
  schemas/maas-backend/itineraries/itinerary-update/request.json
  schemas/maas-backend/itineraries/itinerary-update/response.json
  schemas/maas-backend/profile/profile-favoriteLocations-add/request.json
  schemas/maas-backend/provider/routes/response.json
  schemas/maas-backend/subscriptions/pricing.json
  schemas/maas-backend/subscriptions/subscription.json
  schemas/maas-backend/subscriptions/subscriptionOption.json
  schemas/maas-backend/webhooks/webhooks-payments/gateway/stripe.json
  schemas/tsp/booking-cancel/response.json
  schemas/tsp/booking-create/request.json
  schemas/tsp/booking-create/response.json
  schemas/tsp/booking-options-list/request.json
  schemas/tsp/booking-read-by-id/response.json
  schemas/tsp/booking-receipt/response.json
  schemas/tsp/booking-update/request.json
  schemas/tsp/booking-update/response.json
  schemas/tsp/webhooks-bookings-update/remote-request.json
  schemas/tsp/webhooks-bookings-update/remote-response.json
Labels: PR: Waiting for Review

#405 Add support for new Product property allowFinishTrip
  package.json
  schemas/core/product.json
Labels: PR: Waiting for Review

#420 Fix incorrect fields defined in customers endpoint
  package.json
  schemas/maas-backend/customers/customer.json
  schemas/maas-backend/customers/personalData.json
  schemas/maas-backend/customers/update/request.json
Labels: bug

#423 Fix - Allow choice to have default property set to false
  package.json
  schemas/core/components/configurator.json
Labels: PR: Waiting for Review, bug

#422 Changing regex for zipCode - for NL
  package.json
  schemas/core/components/address.json
  schemas/core/components/geolocation.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#429 Support for "ARRIVED" state
  package.json
  schemas/core/components/state.json
  schemas/tsp/booking-read-by-id/response.json
  schemas/tsp/booking-update/response.json
Labels: PR: Waiting for Review

#430 Bug/booking option create schema default validation
  index.js
  package.json
  schemas/core/components/configurator.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, bug, enhancement
