Repository maasglobal/maas-schemas, pull requests merged in 2019-05, with the labels that each got.

#386 Purchasing app instance id
  package.json
  schemas/tsp/booking-options-list/request.json
Labels: PR: Waiting for Review

#387 Routes query request schema to accept bookingIdToExtend parameter
  package.json
  schemas/maas-backend/routes/routes-query/request.json
Labels: PR: Waiting for Review

#388 Stations schema add zone
  package.json
  schemas/core/components/station.json
  schemas/tsp/stations-list/response.json
  schemas/tsp/stations-retrieve/response.json
Labels: PR: Waiting for Review

#389 Update bookings-create-v2 response w/ new paymentParameters
  package.json
  schemas/maas-backend/bookings/v2/bookings-create/response.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#390 Stations platform code support
  package.json
  schemas/core/components/station.json
  schemas/core/components/units-geo.json
  schemas/tsp/stations-list/response.json
  schemas/tsp/stations-retrieve/response.json
Labels: PR: Waiting for Review

#392 Fix station properties schema
  package.json
  schemas/core/components/station.json
Labels: bug
