Repository maasglobal/maas-schemas, pull requests merged in 2019-04, with the labels that each got.

#377 Fix typo
  package.json
  schemas/core/components/terms.json
Labels: PR: Waiting for Review, bug

#378 Add skip restriction check terms restriction
  package.json
  schemas/core/components/terms.json
Labels: PR: Waiting for Review

#380 Added new type for fare rates.
  package.json
  schemas/core/components/terms.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#379 Booking extension options
  package.json
  schemas/maas-backend/bookings/bookings-agency-options/request.json
  schemas/tsp/booking-options-list/request.json
Labels: PR: Waiting for Review
