Repository maasglobal/maas-schemas, pull requests merged in 2019-03, with the labels that each got.

#360 Amend v2 bookings-create response with JSAPI paymentParameters
  package.json
  schemas/maas-backend/bookings/v2/bookings-create/response.json
  test/feature-validate.js
  test/valid-booking-response-v2-payment-parameters.json
  test/valid-booking-responses-v2-payment-parameters.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#374 fix missing paymentSourceId itinerary update request schema
  package.json
  schemas/maas-backend/itineraries/itinerary-create/request.json
  schemas/maas-backend/itineraries/itinerary-update/request.json
Labels: PR: Waiting for Review, bug

#375 Added new cancellation property cancallationFormActionUrl
  package.json
  schemas/core/components/terms.json
Labels: PR: Waiting for Review
