Repository maasglobal/maas-schemas, pull requests merged in 2019-09, with the labels that each got.

#407 Add immediateUpdate flag to responses
  package.json
  schemas/maas-backend/subscriptions/subscriptions-estimate/response.json
  schemas/maas-backend/subscriptions/subscriptions-update/response.json
Labels: PR: Waiting for Review, enhancement

#408 Support array of payment parameters
  package.json
  schemas/core/components/payment-parameters.json
  schemas/maas-backend/itineraries/itinerary-create/response.json
Labels: PR: Waiting for Review

#411 Fix schemas
  package.json
  schemas/core/components/configurator.json
  schemas/core/itinerary.json
  schemas/core/leg.json
Labels: bug

#416 Vehicle alert schema
  package.json
  schemas/maas-backend/vehicle/vehicle-alert/request.json
  schemas/maas-backend/vehicle/vehicle-alert/response.json
  schemas/tsp/vehicle-alert/request.json
  schemas/tsp/vehicle-alert/response.json
Labels: PR: Waiting for Review
