Repository maasglobal/maas-schemas, pull requests merged in 2020-06, with the labels that each got.

#533 tsp-auth -> verify endpoint
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/tsp-auth/verify/definitions.ts
  maas-schemas-ts/src/maas-backend/tsp-auth/verify/request.ts
  maas-schemas-ts/src/maas-backend/tsp-auth/verify/response.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/tsp-auth/verify/definitions.json
  maas-schemas/schemas/maas-backend/tsp-auth/verify/request.json
  maas-schemas/schemas/maas-backend/tsp-auth/verify/response.json
Labels: PR: WIP

#534 Add missing file to source control
  maas-schemas-ts/src/core/modes/MODE_SHARED_E_BICYCLE.ts
Labels: PR: Waiting for Review, bug

#517 Change personal document consent schema
  maas-schemas-ts/package.json
  maas-schemas-ts/src/core/personal-document.ts
  maas-schemas-ts/src/maas-backend/customers/personal-documents/consent/request.ts
  maas-schemas-ts/src/maas-backend/customers/personal-documents/consent/response.ts
  maas-schemas-ts/src/maas-backend/customers/personal-documents/remove/request.ts
  maas-schemas-ts/src/maas-backend/customers/personal-documents/remove/response.ts
  maas-schemas-ts/src/maas-backend/customers/personal-documents/revoke-consent/request.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/core/personal-document.json
  maas-schemas/schemas/maas-backend/customers/personal-documents/consent/request.json
  maas-schemas/schemas/maas-backend/customers/personal-documents/consent/response.json
  maas-schemas/schemas/maas-backend/customers/personal-documents/remove/request.json
  maas-schemas/schemas/maas-backend/customers/personal-documents/remove/response.json
  maas-schemas/schemas/maas-backend/customers/personal-documents/revoke-consent/request.json
Labels: PR: Waiting for Review

#514 Add missing caret to prettier version
  maas-schemas-ts/package.json
  maas-schemas-ts/yarn.lock
Labels: PR: Can be merged by the reviewer

#536 Verify conversion of new schema files
  maas-schemas-ts/package.json
Labels: PR: Can be merged by the reviewer

#515 Normalize meta currency
  maas-schemas-ts/src/core/components/common.ts
  maas-schemas-ts/src/core/components/fare.ts
  maas-schemas-ts/src/core/customer.ts
  maas-schemas-ts/src/maas-backend/products/provider.ts
  maas-schemas-ts/translation.log
  maas-schemas/schemas/core/components/common.json
  maas-schemas/schemas/core/components/fare.json
  maas-schemas/schemas/core/customer.json
  maas-schemas/schemas/maas-backend/products/provider.json
Labels: PR: Waiting for Review

#545 Bump version to 14.2.0
  maas-schemas-ts/package.json
  maas-schemas/package.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#547 EX-49 - Moved message inside payload
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/itineraries/itinerary-create/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/itineraries/itinerary-create/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#551 EX-49 - Moved message inside payload
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/itineraries/itinerary-create/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/itineraries/itinerary-create/request.json
Labels: PR: Waiting for Review
