Repository maasglobal/maas-schemas, pull requests merged in 2020-05, with the labels that each got.

#526 WS-8691 HSL Student reminder
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/push-notification/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/push-notification/request.json
Labels: PR: Waiting for Review

#529 WS-8691 - Added AuthRequired
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/push-notification/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/push-notification/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, enhancement

#530 E-bicycle support
  maas-schemas-ts/package.json
  maas-schemas-ts/src/core/booking-meta.ts
  maas-schemas-ts/src/core/components/message.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/core/booking-meta.json
  maas-schemas/schemas/core/components/message.json
  maas-schemas/schemas/core/modes/MODE_SHARED_E_BICYCLE.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#532 Added post KYC verification update schema.
  maas-schemas-ts/package.json
  maas-schemas-ts/src/core/personal-document.ts
  maas-schemas-ts/src/tsp/post-kyc-verification-update/request.ts
  maas-schemas-ts/src/tsp/post-kyc-verification-update/response.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/core/personal-document.json
  maas-schemas/schemas/tsp/post-kyc-verification-update/request.json
  maas-schemas/schemas/tsp/post-kyc-verification-update/response.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review
