Repository maasglobal/maas-schemas, pull requests merged in 2020-08, with the labels that each got.

#552 Personal data validation
  maas-schemas-ts/package.json
  maas-schemas-ts/src/core/components/personalDataValidation.ts
  maas-schemas-ts/src/core/customer.ts
  maas-schemas-ts/src/maas-backend/customers/personalData.ts
  maas-schemas-ts/src/maas-backend/products/provider.ts
  maas-schemas-ts/src/maas-backend/subscriptions/subscriptionOption.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/core/components/personalDataValidation.json
  maas-schemas/schemas/core/customer.json
  maas-schemas/schemas/maas-backend/customers/personalData.json
  maas-schemas/schemas/maas-backend/products/provider.json
  maas-schemas/schemas/maas-backend/subscriptions/subscriptionOption.json
Labels: PR: Waiting for Review

#560 Document TypeScript usage
  maas-schemas-ts/README.md
Labels: PR: Can be merged by the reviewer

#562 Change stations schemas to match serverless 1 request
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/stations/stations-list/request.ts
  maas-schemas-ts/src/maas-backend/stations/stations-retrieve/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/stations/stations-list/request.json
  maas-schemas/schemas/maas-backend/stations/stations-retrieve/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#563 Change tsp auth validate for sls 1 request
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/tsp-auth/validate/request.ts
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/tsp-auth/validate/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review

#564 Bug: fix bookings agency-s request for sls 1 convention
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/bookings/bookings-agency-options/request.ts
  maas-schemas-ts/src/maas-backend/bookings/bookings-agency-products/request.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/bookings/bookings-agency-options/request.json
  maas-schemas/schemas/maas-backend/bookings/bookings-agency-products/request.json
Labels: PR: Waiting for Review

#567 Fix product provider retrieve and bump schemas
  maas-schemas-ts/package.json
  maas-schemas-ts/src/maas-backend/products/products-providers-retrieve/request.ts
  maas-schemas-ts/translation.log
  maas-schemas/package.json
  maas-schemas/schemas/maas-backend/products/products-providers-retrieve/request.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review, bug

#561 Add prePurchaseGuidanceUrl to terms
  maas-schemas-ts/package.json
  maas-schemas-ts/src/core/components/terms.ts
  maas-schemas/package.json
  maas-schemas/schemas/core/components/terms.json
Labels: PR: Can be merged by the reviewer, PR: Waiting for Review
